name: floor
description: >
  The typesafe, reactive and lightweight SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.
version: 0.14.0
homepage: https://github.com/vitusortner/floor
author: Vitus Ortner <vitusortner.dev@gmail.com>

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  path: ^1.6.4
  sqflite: ^1.3.0+2
  sqflite_common_ffi: ^1.0.0+2
  floor_annotation:
    git:
      url: 'https://github.com/x459530481/floor_annotation.git'
      ref: 11970268b1de08df7b880e797995920f07559d82
#  floor_annotation:
#    path: ../floor_annotation/
  meta: ^1.1.8
  flutter:
    sdk: flutter

dev_dependencies:
  collection: ^1.14.11
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

  floor_generator:
    git:
      url: 'https://github.com/x459530481/floor_generator.git'
      ref: e13a6dfc98576fda480f8ad66b3fad8460bd7748
#  floor_generator:
#    path: ../floor_generator/
  build_runner: ^1.7.3
  matcher: ^0.12.6
